server:
  port:8080

spring:
  application:
    name:api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-server
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/employee/**