#eureka:
#  client:
#    register-with-eureka: false
#
#server:
#  port: 8888
#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: employee
#          uri: http://localhost:8080
#          predicates:
#            - Path=/api/v1/employee/**
server:
  port: 8888
  name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true